const viewportContainer = document.getElementById('viewport-container');
const toolbar = document.getElementById('toolbar');
const elementSelect = document.getElementById('element-select');
const jointInput = document.getElementById('joint-thickness');
const infoText = document.querySelector('.info-text');
const selectToolButton = document.getElementById('tool-select');
const addToolButton = document.getElementById('tool-add');
const moveToolButton = document.getElementById('tool-move');
const rotateToolButton = document.getElementById('tool-rotate');
const duplicateToolButton = document.getElementById('tool-duplicate');
const deleteToolButton = document.getElementById('tool-delete');
const toolButtons = [selectToolButton, addToolButton, moveToolButton, rotateToolButton, duplicateToolButton, deleteToolButton];
const customElementGroup = document.getElementById('custom-element-group');
const customNameInput = document.getElementById('custom-name');
const customWidthInput = document.getElementById('custom-width');
const customHeightInput = document.getElementById('custom-height');
const customDepthInput = document.getElementById('custom-depth');
const btnOrbitLeft = document.getElementById('btn-orbit-left');
const btnOrbitRight = document.getElementById('btn-orbit-right');
const btnZoomIn = document.getElementById('btn-zoom-in');
const btnZoomOut = document.getElementById('btn-zoom-out');
const placementControlsDiv = document.getElementById('placement-controls');
const dpadUp = document.getElementById('dpad-up');
const dpadDown = document.getElementById('dpad-down');
const dpadLeft = document.getElementById('dpad-left');
const dpadRight = document.getElementById('dpad-right');
const placementRotateLeft = document.getElementById('placement-rotate-left');
const placementRotateRight = document.getElementById('placement-rotate-right');
const dpadUpY = document.getElementById('dpad-up-y'); // Vertical DPad Up
const dpadDownY = document.getElementById('dpad-down-y'); // Vertical DPad Down
const placeButton = document.getElementById('btn-place-element');
const confirmMoveButton = document.getElementById('btn-confirm-move');
const cancelPlacementButton = document.getElementById('btn-cancel-placement');
const cancelMoveButton = document.getElementById('btn-cancel-move');
const contextMenu = document.getElementById('context-menu');
const ctxRotateButton = document.getElementById('ctx-rotate');
const ctxMoveButton = document.getElementById('ctx-move');
const ctxDuplicateButton = document.getElementById('ctx-duplicate');
const ctxDeleteButton = document.getElementById('ctx-delete');
// Assise Controls
const assiseSelect = document.getElementById('assise-select');
const createAssiseButton = document.getElementById('btn-create-assise');
// Save and Open Buttons
const saveButton = document.getElementById('btn-save');
const openButton = document.getElementById('btn-open');
